# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/obsidian',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/obsidian',
                'lib_path': 'obsidian'},
  'syms': {'obsidian.core': {'obsidian.core.foo': ('core.html#foo', 'obsidian/core.py')}}}
